# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=180, null=True)),
                ('location', models.CharField(blank=True, max_length=180, null=True)),
                ('fee', models.FloatField(blank=True, max_length=20, null=True)),
                ('camera', models.CharField(blank=True, choices=[('SLR', 'SLR'), ('Nikon', 'Nikon'), ('Cannon', 'Cannon'), ('Digital', 'Digital'), ('Analog', 'Analog')], max_length=50, null=True)),
                ('services', models.CharField(blank=True, choices=[('Wedding', 'Wedding'), ('Senior Photos', 'Senior Pictures'), ('Family Photos', 'Family Photos'), ('Sports Photography', 'Sports Photo'), ('City and Rural Landscapes', 'Landscapes')], max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_styles', models.CharField(blank=True, choices=[('Black and White', 'BW'), ('Color', 'Color'), ('Photoshop Ability', 'Photoshop')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
